# Generated by Django 2.1.7 on 2019-03-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderAPI', '0002_userinfo_constellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetsinfo',
            name='PubTime',
            field=models.CharField(blank=True, max_length=300, verbose_name='发表时间'),
        ),
    ]
