# Generated by Django 2.1.7 on 2019-04-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderAPI', '0003_auto_20190330_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetsinfo',
            name='PubTime',
            field=models.DateTimeField(blank=True, verbose_name='发表时间'),
        ),
    ]
