# Generated by Django 2.1.7 on 2019-04-11 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderAPI', '0005_auto_20190409_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField(verbose_name='微博内容')),
                ('tags', models.TextField(verbose_name='标签')),
                ('pinyin', models.TextField(verbose_name='拼音')),
                ('sentiments', models.IntegerField(verbose_name='情感值')),
                ('UserInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpiderAPI.UserInfo', verbose_name='用户信息')),
            ],
            options={
                'verbose_name': '情感分析',
                'verbose_name_plural': '情感分析',
            },
        ),
    ]
