# Generated by Django 2.1.7 on 2019-04-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderAPI', '0006_sentimentsinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentsinfo',
            name='sentiments',
            field=models.CharField(max_length=50, verbose_name='情感值'),
        ),
    ]
