# Generated by Django 2.1.7 on 2019-04-11 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderAPI', '0007_auto_20190411_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetsinfo',
            name='crawl_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='tweetsinfo',
            name='pinyin',
            field=models.TextField(blank=True, verbose_name='拼音'),
        ),
        migrations.AddField(
            model_name='tweetsinfo',
            name='sentiments',
            field=models.CharField(blank=True, max_length=50, verbose_name='情感值'),
        ),
        migrations.AddField(
            model_name='tweetsinfo',
            name='tags',
            field=models.TextField(blank=True, verbose_name='标签'),
        ),
    ]
