# Generated by Django 2.1.7 on 2019-04-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderAPI', '0009_auto_20190412_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='cookie',
            field=models.TextField(blank=True, verbose_name='设置cookie'),
        ),
    ]
