# Generated by Django 2.1.7 on 2019-04-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderAPI', '0010_auto_20190412_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='URL',
            field=models.CharField(blank=True, max_length=300, verbose_name='首页链接'),
        ),
    ]
