# Generated by Django 2.1.7 on 2019-04-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderAPI', '0011_auto_20190412_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentweiboinfo',
            name='wb_like',
            field=models.IntegerField(blank=True, default=0, verbose_name='点赞数'),
        ),
    ]
