# Generated by Django 2.1.7 on 2019-04-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapydAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='用户id'),
        ),
    ]
