# Generated by Django 2.1.7 on 2019-04-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapydAPI', '0002_auto_20190403_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentinfo',
            name='comment_user_id',
            field=models.CharField(max_length=50, verbose_name='评论的用户ID'),
        ),
    ]
