# Generated by Django 2.1.7 on 2019-04-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapydAPI', '0004_target_isscrapy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='isScrapy',
            field=models.IntegerField(default=0, verbose_name='是否爬取'),
        ),
    ]
