# Generated by Django 2.1.7 on 2019-05-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapydAPI', '0005_auto_20190425_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Image',
            field=models.TextField(blank=True, verbose_name='用户头像'),
        ),
    ]
