# Generated by Django 2.1.7 on 2019-05-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapydAPI', '0006_userinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='group',
            field=models.IntegerField(default=0, verbose_name='是否爬取'),
        ),
    ]
