# Generated by Django 2.1.7 on 2019-05-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapydAPI', '0007_target_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='group',
            field=models.IntegerField(default=0, verbose_name='用户分组'),
        ),
    ]
